locale                   : "en-US"
site_theme               : "default"
title                    : "Thibault Fieve"
title_separator          : "-"
name                     : &name "Thibault Fieve"
description              : &description "Hult Boston 2026"
url                      : https://thibaultfieve.github.io
baseurl                  : ""
repository               : "tfievespam-jpg/thibaultfieve.github.io"

author:
  avatar           : "profile.png"
  name             : "Thibault Fieve"
  pronouns         :
  bio              : "Master Student at Hult"
  location         : "Boston,MA"
  employer         :
  uri              :
  email            : "tfieve@student.hult.edu"
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=YUy98TUAAAAJ&hl=en&authuser=1"
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "tfievespam-jpg"
  kaggle           :
  stackoverflow    :
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "thibault-fieve"
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

# NAVIGATION — seulement About et CV
header_pages:
  - _pages/about.md
  - _pages/cv.md

publication_category:
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :

atom_feed:
  hide                   : true

analytics:
  provider               : "false"

include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
